//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.19 at 04:19:32 PM ICT 
//


package org.ganglia.client4j.internal;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hostOrHOSTSOrMETRICS"
})
@XmlRootElement(name = "CLUSTER")
public class CLUSTER {

    @XmlAttribute(name = "NAME", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "OWNER")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String owner;
    @XmlAttribute(name = "LATLONG")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String latlong;
    @XmlAttribute(name = "URL")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String url;
    @XmlAttribute(name = "LOCALTIME", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String localtime;
    @XmlElements({
        @XmlElement(name = "HOST", type = HOST.class),
        @XmlElement(name = "HOSTS", type = HOSTS.class),
        @XmlElement(name = "METRICS", type = METRICS.class)
    })
    protected List<Object> hostOrHOSTSOrMETRICS;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOWNER() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOWNER(String value) {
        this.owner = value;
    }

    /**
     * Gets the value of the latlong property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLATLONG() {
        return latlong;
    }

    /**
     * Sets the value of the latlong property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLATLONG(String value) {
        this.latlong = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURL() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURL(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the localtime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLOCALTIME() {
        return localtime;
    }

    /**
     * Sets the value of the localtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLOCALTIME(String value) {
        this.localtime = value;
    }

    /**
     * Gets the value of the hostOrHOSTSOrMETRICS property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hostOrHOSTSOrMETRICS property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHOSTOrHOSTSOrMETRICS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HOST }
     * {@link HOSTS }
     * {@link METRICS }
     * 
     * 
     */
    public List<Object> getHOSTOrHOSTSOrMETRICS() {
        if (hostOrHOSTSOrMETRICS == null) {
            hostOrHOSTSOrMETRICS = new ArrayList<Object>();
        }
        return this.hostOrHOSTSOrMETRICS;
    }

    public String toString() {
        StringBuffer buf = new StringBuffer("<CLUSTER NAME=\"" + getNAME() + "\" LOCALTIME=\"" + getLOCALTIME() + "\" OWNER=\"" + getOWNER() + "\" LATLONG=\"" + getLATLONG() + "\" URL=\"" + getURL() + "\">\n");
        List<Object> objects = getHOSTOrHOSTSOrMETRICS();
        if (objects != null) {
           for (Object object : objects) {
              buf.append(object.toString());
           }
        }         
        buf.append("</CLUSTER>\n");
        return buf.toString();
    }

}
