//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.19 at 04:19:32 PM ICT 
//


package org.ganglia.client4j.internal;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "extraelement"
})
@XmlRootElement(name = "EXTRA_DATA")
public class EXTRADATA {

    @XmlElement(name = "EXTRA_ELEMENT")
    protected List<EXTRAELEMENT> extraelement;

    /**
     * Gets the value of the extraelement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extraelement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEXTRAELEMENT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EXTRAELEMENT }
     * 
     * 
     */
    public List<EXTRAELEMENT> getEXTRAELEMENT() {
        if (extraelement == null) {
            extraelement = new ArrayList<EXTRAELEMENT>();
        }
        return this.extraelement;
    }

    public String toString() {
        StringBuffer buf = new StringBuffer("<EXTRA_DATA>\n");
        List<EXTRAELEMENT> extras = getEXTRAELEMENT();
        if (extras != null) {
           for (EXTRAELEMENT extra : extras) {
              buf.append(extra.toString());
           }
        }
        buf.append("</EXTRA_DATA>\n");
        return buf.toString();
    }

}
