//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.19 at 04:19:32 PM ICT 
//


package org.ganglia.client4j.internal;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gridOrCLUSTEROrHOST"
})
@XmlRootElement(name = "GANGLIA_XML")
public class GANGLIAXML {

    @XmlAttribute(name = "VERSION", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String version;
    @XmlAttribute(name = "SOURCE", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String source;
    @XmlElements({
        @XmlElement(name = "GRID", type = GRID.class),
        @XmlElement(name = "CLUSTER", type = CLUSTER.class),
        @XmlElement(name = "HOST", type = HOST.class)
    })
    protected List<Object> gridOrCLUSTEROrHOST;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVERSION() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVERSION(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSOURCE() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSOURCE(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the gridOrCLUSTEROrHOST property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gridOrCLUSTEROrHOST property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGRIDOrCLUSTEROrHOST().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GRID }
     * {@link CLUSTER }
     * {@link HOST }
     * 
     * 
     */
    public List<Object> getGRIDOrCLUSTEROrHOST() {
        if (gridOrCLUSTEROrHOST == null) {
            gridOrCLUSTEROrHOST = new ArrayList<Object>();
        }
        return this.gridOrCLUSTEROrHOST;
    }

    public String toString() {
        StringBuffer buf = new StringBuffer("<GANGLIA_XML VERSION=\"" + getVERSION() + "\" SOURCE=\"" + getSOURCE() + "\">\n");
        List<Object> objects = getGRIDOrCLUSTEROrHOST(); 
        if (objects != null) {
           for (Object object : objects) {
              buf.append(object.toString());
           }
        }      
        buf.append("</GANGLIA_XML>\n");
        return buf.toString();
    }

}
