//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.19 at 04:19:32 PM ICT 
//


package org.ganglia.client4j.internal;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "metric"
})
@XmlRootElement(name = "HOST")
public class HOST {

    @XmlAttribute(name = "NAME", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "IP", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String ip;
    @XmlAttribute(name = "LOCATION")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String location;
    @XmlAttribute(name = "TAGS")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String tags;
    @XmlAttribute(name = "REPORTED", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String reported;
    @XmlAttribute(name = "TN")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String tn;
    @XmlAttribute(name = "TMAX")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String tmax;
    @XmlAttribute(name = "DMAX")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String dmax;
    @XmlAttribute(name = "GMOND_STARTED")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String gmondstarted;
    @XmlElement(name = "METRIC")
    protected List<METRIC> metric;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the ip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIP() {
        return ip;
    }

    /**
     * Sets the value of the ip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIP(String value) {
        this.ip = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLOCATION() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLOCATION(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the tags property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAGS() {
        return tags;
    }

    /**
     * Sets the value of the tags property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAGS(String value) {
        this.tags = value;
    }

    /**
     * Gets the value of the reported property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREPORTED() {
        return reported;
    }

    /**
     * Sets the value of the reported property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREPORTED(String value) {
        this.reported = value;
    }

    /**
     * Gets the value of the tn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTN() {
        return tn;
    }

    /**
     * Sets the value of the tn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTN(String value) {
        this.tn = value;
    }

    /**
     * Gets the value of the tmax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTMAX() {
        return tmax;
    }

    /**
     * Sets the value of the tmax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTMAX(String value) {
        this.tmax = value;
    }

    /**
     * Gets the value of the dmax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDMAX() {
        return dmax;
    }

    /**
     * Sets the value of the dmax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDMAX(String value) {
        this.dmax = value;
    }

    /**
     * Gets the value of the gmondstarted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGMONDSTARTED() {
        return gmondstarted;
    }

    /**
     * Sets the value of the gmondstarted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGMONDSTARTED(String value) {
        this.gmondstarted = value;
    }

    /**
     * Gets the value of the metric property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metric property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMETRIC().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link METRIC }
     * 
     * 
     */
    public List<METRIC> getMETRIC() {
        if (metric == null) {
            metric = new ArrayList<METRIC>();
        }
        return this.metric;
    }

    public String toString() {
        StringBuffer buf = new StringBuffer("<HOST ");
        buf.append("NAME=\"" + getNAME() + "\" ");
        buf.append("IP=\"" + getIP() + "\" ");
        buf.append("REPORTED=\"" + getREPORTED() + "\" ");
        buf.append("TN=\"" + getTN() + "\" ");
        buf.append("TMAX=\"" + getTMAX() + "\" ");
        buf.append("DMAX=\"" + getDMAX() + "\" ");
        buf.append("LOCATION=\"" + getLOCATION() + "\" ");
        buf.append("GMOND_STARTED=\"" + getGMONDSTARTED() + "\" ");
        buf.append("TAGS=\"" + getTAGS() + "\">\n");
        List<METRIC> metrics = getMETRIC();
        if (metrics != null) {
           for (METRIC metric : metrics) {
              buf.append(metric.toString());
           }
        }
        buf.append("</HOST>\n");
        return buf.toString();
    }
}
